Repository AY1920S2-CS2113-T14-1/tp, pull requests merged in 2020-03, with the labels that each got.

#38 Use Locale.US when specifying date format to avoid inconsistencies in…
  src/main/java/seedu/tp/parser/Parser.java
  src/main/java/seedu/tp/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#63 Fix bug where user can add the same flashcard to a group twice.
  src/main/java/seedu/tp/Main.java
  src/main/java/seedu/tp/exceptions/DuplicateFlashcardException.java
  src/main/java/seedu/tp/flashcard/FlashcardList.java
  src/main/java/seedu/tp/group/FlashcardGroup.java
  src/main/java/seedu/tp/ui/Ui.java
Labels: severity.Low, type.Bug

#127 Update help message
  src/main/java/seedu/tp/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task
